# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'The New Canvas'
tagline:          'A few things to do with a laptop in your hands.'
url:              http://mrgreenh.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Carlo Andrea Conte'
  url:            https://twitter.com/mrgreenh

# Custom vars
