# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The New Canvas
tagline:          'A few things to do with a laptop in your hands.'
description:      '<em>About the author:</em> Carlo Andrea Conte is... Someone who needs to think about what to write in here.'
url:              http://mrgreenh.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Carlo Andrea Conte'
  url:            https://twitter.com/mrgreenh

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mrgreenh
